/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    BrunchMenu: typeof import('./src/components/BrunchMenu.vue')['default']
    CafeMenu: typeof import('./src/components/CafeMenu.vue')['default']
    Events: typeof import('./src/components/Events.vue')['default']
    FoodMenu: typeof import('./src/components/FoodMenu.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IconBiCup: typeof import('~icons/bi/cup')['default']
    IconBiTelephone: typeof import('~icons/bi/telephone')['default']
    IconLucideCoffee: typeof import('~icons/lucide/coffee')['default']
    IconLucideCroissant: typeof import('~icons/lucide/croissant')['default']
    IconLucideUtensils: typeof import('~icons/lucide/utensils')['default']
    IconLucideWine: typeof import('~icons/lucide/wine')['default']
    IconMaterialSymbolsArrowDropDown: typeof import('~icons/material-symbols/arrow-drop-down')['default']
    IconMaterialSymbolsArrowDropDownCircleOutline: typeof import('~icons/material-symbols/arrow-drop-down-circle-outline')['default']
    IconMaterialSymbolsCalendarMonthOutline: typeof import('~icons/material-symbols/calendar-month-outline')['default']
    IconMaterialSymbolsKeyboardArrowDown: typeof import('~icons/material-symbols/keyboard-arrow-down')['default']
    IconMaterialSymbolsKeyboardArrowDownRounded: typeof import('~icons/material-symbols/keyboard-arrow-down-rounded')['default']
    IconMaterialSymbolsMapOutline: typeof import('~icons/material-symbols/map-outline')['default']
    IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IconMingcuteTeacupLine: typeof import('~icons/mingcute/teacup-line')['default']
    Lineup: typeof import('./src/components/Lineup.vue')['default']
    LineupDivider: typeof import('./src/components/LineupDivider.vue')['default']
    LineupEvent: typeof import('./src/components/LineupEvent.vue')['default']
    LoungeMenu: typeof import('./src/components/LoungeMenu.vue')['default']
    MenuDivider: typeof import('./src/components/MenuDivider.vue')['default']
    MenuDividerBackground: typeof import('./src/components/MenuDivider-background.vue')['default']
    MenuItems: typeof import('./src/components/MenuItems.vue')['default']
    MenuSection: typeof import('./src/components/MenuSection.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    StoreInfo: typeof import('./src/components/StoreInfo.vue')['default']
    StoreInfoDivider: typeof import('./src/components/StoreInfoDivider.vue')['default']
  }
}
